Repository uniorunr/cj-3-teamwork, pull requests merged in 2019-01, with the labels that each got.

#32 Update styles
  src/components/container/Home/MainContent/MainContent.css
  src/components/container/ListDirectors/SearchByList/CardDirector.css
  src/components/container/ListDirectors/VideoOverlay/VideoOverlay.css
  src/components/presentetion/NavBarItem/NavBarItem.css
Labels: style

#39 Add director Info to the page about director
  src/components/container/ListDirectors/ListDirectors.css
  src/components/container/ListDirectors/ListDirectors.jsx
Labels: enhancement

#46 Update website title
  src/index.html
Labels: invalid

#48 #45 Add adaptability of elements on the homepage
  src/components/App.css
  src/components/container/Home/Home.css
  src/components/container/Home/MainContent/MainContent.css
  src/components/container/Home/MainFooter/MainFooter.css
  src/components/presentetion/DeveloperItem/DeveloperItem.css
  src/components/presentetion/NavBarItem/NavBarItem.css
Labels: style

#63 #62 Add adaptive style for list directors
  src/components/container/ListDirectors/SearchByList/CardDirector.css
Labels: style
